  
name: Run checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: src/

    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v4.0.0

    - name: Install dependencies
      run: |
        luarocks install luacheck

    - name: Run linter
      run: |
        luacheck --no-color ./src
